[build]
builder = "nixpacks"
buildCommand = "npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy && npm run build"

[deploy]
startCommand = "node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

